KaskKiosk/Controllers/AppController.cs
using KaskKiosk.AESApplicationServiceRef;

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace KaskKiosk.Controllers
{
    public class AppController : Controller
    {
        readonly string generalDateFormat = "M/yyyy";
        readonly string generalTimeFormat = "{0:hh\\:mm}";

        [Authorize(Roles = "Administrator, HiringManager")]
        public async Task<ActionResult> Index()
        {
            var apps = await ServerResponse<List<ApplicationDAO>>.GetResponseAsync(ServiceURIs.ServiceApplicationUri);
            List<string> allowableActions = new List<string>();

            if (this.User.IsInRole("HiringManager"))
            {
                allowableActions.Add("approve");
                allowableActions.Add("reject");
            }

            ViewBag.allowableActions = allowableActions;
            ViewBag.applications = apps;
            return View();
        }

        [AllowAnonymous]
        public async Task<ActionResult> Create()
        {
            var jobs = await ServerResponse<List<JobDAO>>.GetResponseAsync(ServiceURIs.ServiceJobUri);
            List<String> timePickerList = new List<String>();

            // create time picker range (in hours)
            for (int i = 0; i < 24; i++)
            {
                timePickerList.Add(i.ToString());
            }

            ViewBag.baseURL = Url.Content("~/");
            ViewBag.jobs = jobs;
            ViewBag.timePickerList = timePickerList;
            return View();
        }

        /// ********************************************************************** ///
        ///     In fact, we can make a viewmodel and populate our data with it.    ///
        /// ********************************************************************** ///

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Create(FormCollection collection)
        {
            try
            {
                if (!string.IsNullOrEmpty(Request.Form["FirstName"]) && !string.IsNullOrEmpty(Request.Form["LastName"]) && !string.IsNullOrEmpty(Request.Form["SSN"]) && Request.Form["acknowledgeAccurateDataCheckbox"] != null)
                {
                    // save application form data back to database through service
                    using (HttpClient httpClient = new HttpClient())
                    {
                        httpClient.BaseAddress = new Uri("http://localhost:51309");
                        httpClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                        HttpResponseMessage result = new HttpResponseMessage();
                        string resultContent = "";

                        // gather Applicant form data
                        ApplicantDAO applicant = new ApplicantDAO();
                        applicant.FirstName = Request.Form["FirstName"];
                        applicant.MiddleName = Request.Form["MiddleName"];
                        applicant.LastName = Request.Form["LastName"];
                        applicant.SSN = Request.Form["SSN"];
                        applicant.ApplicantAddress = Request.Form["ApplicantAddress"];
                        applicant.Phone = Request.Form["ApplicantPhone"];
                        applicant.NameAlias = Request.Form["NameAlias"];

                        // post (save) applicant data
                        result = httpClient.PostAsJsonAsync(ServiceURIs.ServiceApplicantUri, applicant).Result;
                        resultContent = result.Content.ReadAsStringAsync().Result;

                        // gather Application form data
                        ApplicationDAO application = new ApplicationDAO();
                        application.ApplicationStatus = "Submitted";
                        application.SalaryExpectation = Request.Form["SalaryExpectation"];
                        application.FullTime = Convert.ToByte(Request.Form["FullTime"]);
                        application.AvailableForDays = Convert.ToByte(Request.Form["AvailableForDays"]);
                        application.AvailableForEvenings = Convert.ToByte(Request.Form["AvailableForEvenings"]);
                        application.AvailableForWeekends = Convert.ToByte(Request.Form["AvailableForWeekends"]);
                        application.MondayFrom = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["MondayFrom"]));
                        application.TuesdayFrom = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["TuesdayFrom"]));
                        application.WednesdayFrom = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["WednesdayFrom"]));
                        application.ThursdayFrom = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["ThursdayFrom"]));
                        application.FridayFrom = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["FridayFrom"]));
                        application.SaturdayFrom = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["SaturdayFrom"]));
                        application.SundayFrom = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["SundayFrom"]));
                        application.MondayTo = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["MondayTo"]));
                        application.TuesdayTo = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["TuesdayTo"]));
                        application.WednesdayTo = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["WednesdayTo"]));
                        application.ThursdayTo = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["ThursdayTo"]));
                        application.FridayTo = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["FridayTo"]));
                        application.SaturdayTo = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["SaturdayTo"]));
                        application.SundayTo = System.TimeSpan.FromHours(Convert.ToDouble(Request.Form["SundayTo"]));

                        // post (save) application data
                        result = httpClient.PostAsJsonAsync(ServiceURIs.ServiceApplicationUri, application).Result;
                        resultContent = result.Content.ReadAsStringAsync().Result;

                        // get correct applicant id
                        // TODO: there is still something we might need to change about this...
                        // ***** We don't, it's safe to assume that id would be the last item on the list
                        // since we're using auto incremented id. *****
                        var applicants = await ServerResponse<List<ApplicantDAO>>.GetResponseAsync(ServiceURIs.ServiceApplicantUri); ;
                        applicant.ApplicantID = applicants.Last().ApplicantID;

                        // get correct application id
                        // TODO: there is still something we might need to change about this...
                        var applications = await ServerResponse<List<ApplicationDAO>>.GetResponseAsync(ServiceURIs.ServiceApplicationUri);
                        application.ApplicationID = applications.Last().ApplicationID;

                        // Create Applied DAO;
                        AppliedDAO applied = new AppliedDAO();
                        applied.ApplicantID = applicant.ApplicantID;
                        applied.ApplicationID = application.ApplicationID;
                        applied.JobOpeningID = Convert.ToInt32(Request.Form["JobOpeningIDReferenceNumber"]);
                        applied.DateApplied = DateTime.Now;

                        // post (save) applied data
                        result = httpClient.PostAsJsonAsync(ServiceURIs.ServiceAppliedUri, applied).Result;
                        resultContent = result.Content.ReadAsStringAsync().Result;

                        // gather Employer data
                        EmployerDAO employer = new EmployerDAO();
                        var employers = await ServerResponse<List<EmployerDAO>>.GetResponseAsync(ServiceURIs.ServiceEmployerUri);
                        EmploymentDAO employment = new EmploymentDAO();

                        for (int i = 1; i < 4; i++)
                        {
                            // make sure this form item is filled in...
                            if ((!string.IsNullOrWhiteSpace(Request.Form["EmployerName_" + i]) &&
                                  !string.IsNullOrWhiteSpace(Request.Form["EmployerAddress_" + i])))
                            {
                                employer.Name = Request.Form["EmployerName_" + i];
                                employer.EmployerAddress = Request.Form["EmployerAddress_" + i];
                                if (!string.IsNullOrWhiteSpace(Request.Form["EmployerPhone_" + i]))
                                    employer.PhoneNumber = Request.Form["EmployerPhone_" + i];

                                //if (!string.IsNullOrWhiteSpace(employer.Name))
                                //{
                                // TODO: check if employer already exists in database
                                // TODO: if employer exists in database: don't insert data
                                // if employer !exists in database: insert data

                                // post (save) employer data
                                result = httpClient.PostAsJsonAsync(ServiceURIs.ServiceEmployerUri, employer).Result;
                                resultContent = result.Content.ReadAsStringAsync().Result;
                                //}

                                // get correct employer id
                                // TODO: there is still something we might need to change about this...

KaskKiosk/Views/App/Approve.cshtml
@{
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
    ViewBag.Title = "Approve Application";
}

<h2>Approve Application</h2>
@using (Html.BeginForm("Approve", "App", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="section" id="section0">
        <h3>Are you sure you want to approve this application?</h3>
        <input type="hidden" name="ApplicationID" id="ApplicationID" value="@ViewBag.applicationID" />
        <br style="clear:both;"/>
    </div>
    
    <a href="@Html.Encode("/App/Index")" class="btn btn-danger">Cancel</a>@Html.Raw("&nbsp;&nbsp;&nbsp;")
    <input type="submit" id="submit" value="Approve" class="btn btn-success" />
}

KaskKiosk/Views/App/Index.cshtml
@model IEnumerable<KaskKiosk.AESApplicationServiceRef.ApplicationDAO>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>All Applications</h2>
<table class="table table-striped">
    <tr>
        <th>id</th>
        <th>Application Status</th>
        <th>Actions</th>
    </tr>
@foreach (var item in ViewBag.applications)
{
    <tr>
        <td>@item.ApplicationID</td>
        <td>@item.ApplicationStatus</td>
        <td>
             @foreach (var allowedAction in @ViewBag.allowableActions)
            {
                if(allowedAction == "approve")
                {
                    @Html.ActionLink("Approve", "Approve", new { id=item.ApplicationID })
                    @Html.Raw(" | ")
                }
                if(allowedAction == "reject")
                {
                    @Html.ActionLink("Reject", "Reject", new { id=item.ApplicationID })
                    @Html.Raw(" | ")
                }
            }
            @Html.ActionLink("View Details", "Details", new { id=item.ApplicationID })
        </td>
    </tr>
}
</table>

KaskKiosk/Views/App/Reject.cshtml
@{
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
    ViewBag.Title = "Reject Application";
}

<h2>Reject Application</h2>
@using (Html.BeginForm("Reject", "App", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="section" id="section0">
        <h3>Are you sure you want to reject this application?</h3>
        <input type="hidden" name="ApplicationID" id="ApplicationID" value="@ViewBag.applicationID" />
        <br style="clear:both;"/>
    </div>
    
    <a href="@Html.Encode("/App/Index")" class="btn btn-danger">Cancel</a>@Html.Raw("&nbsp;&nbsp;&nbsp;")
    <input type="submit" id="submit" value="Reject" class="btn btn-success" />
}

KaskKiosk/Views/App/Status.cshtml
@model IEnumerable<KaskKiosk.AESApplicationServiceRef.ApplicationDAO>

@{
    ViewBag.Title = "Your Applications";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>Your Applications</h2>
<table class="table table-striped">
    <tr>
        <th>id</th>
        <th>Application Status</th>
    </tr>
@foreach (var item in ViewBag.applications)
{
    <tr>
        <td>@item.ApplicationID</td>
        <td>@item.ApplicationStatus</td>
    </tr>
}
</table>