KaskKiosk/Controllers/API/JobOpeningController.cs
using KaskKiosk.AESApplicationServiceRef;
using System.Collections.Generic;
using System.ServiceModel;
using System.Web;
using System.Web.Http;

namespace KaskKiosk.Controllers.API
{
    public class JobOpeningController : ApiController
    {
        // GET: /JobOpening/
        [HttpGet]
        public IEnumerable<JobOpeningDAO> GetJobOpenings()
        {
            JobOpeningServiceClient client = new JobOpeningServiceClient();

            try
            {
                IEnumerable<JobOpeningDAO> result = client.GetJobOpenings();
                return result;
            }
            catch (FaultException<KaskServiceException> e)
            {
                throw new HttpException(e.Message);
            }
        }

        // GET: /JobOpening/id
        [HttpGet]
        public JobOpeningDAO GetJobOpening(int id)
        {
            JobOpeningServiceClient client = new JobOpeningServiceClient();

            try
            {
                JobOpeningDAO result = client.GetJobOpeningByID(id);
                return result;
            }
            catch (FaultException<KaskServiceException> e)
            {
                throw new HttpException(e.Message);
            }
        }

        [HttpPost]
        public bool PostJobOpening(JobOpeningDAO jobOpening)
        {
            JobOpeningServiceClient client = new JobOpeningServiceClient();

            try
            {
                bool result = false;

                // are we editing or creating this item?
                if (jobOpening.JobOpeningID > 0)
                    result = client.UpdateJobOpening(jobOpening);
                else
                    result = client.CreateJobOpening(jobOpening);

                return result;
            }
            catch (FaultException<KaskServiceException> e)
            {
                throw new HttpException(e.Message);
            }
        }
    }
}

KaskKiosk/Controllers/JobOpeningsController.cs
using KaskKiosk.AESApplicationServiceRef;

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KaskKiosk.Controllers
{
    public class JobOpeningsController : Controller
    {
        //
        // GET: /JobOpenings/

        [Authorize(Roles = "Administrator, HiringManager, StoreManager")]
        public async Task<ActionResult> Index()
        {
            List<JobDAO> jobs = await ServerResponse<List<JobDAO>>.GetResponseAsync(ServiceURIs.ServiceJobUri);
            List<JobOpeningDAO> jobOpenings = await ServerResponse<List<JobOpeningDAO>>.GetResponseAsync(ServiceURIs.ServiceJobOpeningUri);
            List<string> allowableActions = new List<string>();
            
            if (this.User.IsInRole("StoreManager"))
            {
                allowableActions.Add("approve");
                allowableActions.Add("reject");
            }
   
            ViewBag.allowableActions = allowableActions;
            ViewBag.jobs = jobs;
            ViewBag.jobOpenings = jobOpenings;
            return View();
        }

        //
        // GET: /JobOpenings/Details/5

        [Authorize(Roles = "Administrator, HiringManager, StoreManager")]
        public async Task<ActionResult> Details(int id)
        {
            List<JobDAO> jobs = await ServerResponse<List<JobDAO>>.GetResponseAsync(ServiceURIs.ServiceJobUri);
            JobOpeningDAO jobOpening = await ServerResponse<JobOpeningDAO>.GetResponseAsync(ServiceURIs.ServiceJobOpeningUri + "/" + id);
            List<JobRequirementDAO> jobRequirements = await ServerResponse<List<JobRequirementDAO>>.GetResponseAsync(ServiceURIs.ServiceJobRequirementUri);
            List<SkillDAO> skills = await ServerResponse<List<SkillDAO>>.GetResponseAsync(ServiceURIs.ServiceSkillUri);
            List<StoreDAO> stores = await ServerResponse<List<StoreDAO>>.GetResponseAsync(ServiceURIs.ServiceStoreUri);

            // TODO: refactor this section so that we only find relevant
            // job requirements for this job opening...
            // at the moment, we loop through all job requirements and pick out what we want

            ViewBag.baseURL = Url.Content("~/");
            ViewBag.jobs = jobs;
            ViewBag.jobOpening = jobOpening;
            ViewBag.jobRequirements = jobRequirements;
            ViewBag.skills = skills;
            ViewBag.stores = stores;
            return View();
        }

        //
        // GET: /JobOpenings/Create
        [Authorize(Roles = "Administrator, HiringManager, StoreManager")]
        public async Task<ActionResult> Create()
        {
            List<JobDAO> jobs = await ServerResponse<List<JobDAO>>.GetResponseAsync(ServiceURIs.ServiceJobUri);
            List<SkillDAO> skills = await ServerResponse<List<SkillDAO>>.GetResponseAsync(ServiceURIs.ServiceSkillUri);
            List<StoreDAO> stores = await ServerResponse<List<StoreDAO>>.GetResponseAsync(ServiceURIs.ServiceStoreUri);
            List<SAQuestionDAO> saQuestions = await ServerResponse<List<SAQuestionDAO>>.GetResponseAsync(ServiceURIs.ServiceSAQuestionUri);

            ViewBag.baseURL = Url.Content("~/");
            ViewBag.stores = stores;
            ViewBag.jobs = jobs;
            ViewBag.skills = skills;
            ViewBag.saQuestions = saQuestions;
            return View();
        }

        //
        // POST: /JobOpenings/Create

        [HttpPost]
        [Authorize(Roles = "Administrator, HiringManager, StoreManager")]
        public async Task<ActionResult> Create(FormCollection collection)
        {
            try
            {
                if (!string.IsNullOrEmpty(Request.Form["JobID"]))
                {
                    // save application form data back to database through service
                    using (HttpClient httpClient = new HttpClient())
                    {
                        httpClient.BaseAddress = new Uri("http://localhost:51309");
                        httpClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                        HttpResponseMessage result = new HttpResponseMessage();
                        string resultContent = "";

                        // gather JobOpening form data
                        JobOpeningDAO jobOpening = new JobOpeningDAO();
                        jobOpening.OpenDate = DateTime.Now; // note: this could change to the above "OpenDate" line of code in the future...
                        jobOpening.JobID = Convert.ToInt32(Request.Form["JobID"]);
                        jobOpening.Approved = 0;    // "not approved" by default
                        jobOpening.Description = Request.Form["Description"];
                        jobOpening.StoreID = Convert.ToInt32(Request.Form["StoreID"]);

                        // post (save) JobOpening data
                        result = httpClient.PostAsJsonAsync(ServiceURIs.ServiceJobOpeningUri, jobOpening).Result;
                        resultContent = result.Content.ReadAsStringAsync().Result;

                        // save job requirement data
                        // 1. see which checkboxes are checked
                        // 2. create new JobRequirement entries and tie those back to this JobOpening

                        // get correct job opening id of the job opening we just saved
                        var jobOpenings = await ServerResponse<List<JobOpeningDAO>>.GetResponseAsync(ServiceURIs.ServiceJobOpeningUri);
                        int jobOpeningId = jobOpenings.Last().JobOpeningID;

                        // TODO: change the hardcoded "50" into the length of all available skills
                        for (int i = 0; i < 50; i++)
                        {
                            try
                            {
                                if (Request.Form["Skill_" + i] != null)
                                {
                                    // NOTE: renamed Job_ID to JobOpening_ID in JobRequirement table?
                                    // because we aren't really linking these requirements to a "job type" in the Job table
                                    // we are actually linking these to JobOpenings...
                                    JobRequirementDAO jobRequirement = new JobRequirementDAO();
                                    jobRequirement.JobOpeningID = jobOpeningId;
                                    jobRequirement.SkillID = i;

                                    // post (save) JobRequirement data
                                    result = httpClient.PostAsJsonAsync(ServiceURIs.ServiceJobRequirementUri, jobRequirement).Result;
                                    resultContent = result.Content.ReadAsStringAsync().Result;
                                }
                            }
                            catch { }
                        }

                        // TODO: change the hardcoded "50" into the length of all available short answer questions
                        for (int i = 0; i < 50; i++)
                        {
                            try
                            {
                                if (Request.Form["SAQuestion_" + i] != null)
                                {
                                    JobOpeningInterviewQuestionDAO jobOpeningInterviewQuestion = new JobOpeningInterviewQuestionDAO();
                                    jobOpeningInterviewQuestion.JobOpeningID = jobOpeningId;
                                    jobOpeningInterviewQuestion.SAQuestionID = Convert.ToInt32(Request.Form["SAQuestion_" + i]);

                                    // post (save) which SA Questions we want to use for this Job Opening
                                    result = httpClient.PostAsJsonAsync(ServiceURIs.ServiceJobOpeningInterviewQuestionUri, jobOpeningInterviewQuestion).Result;
                                    resultContent = result.Content.ReadAsStringAsync().Result;
                                }
                            }
                            catch { }
                        }
                    }

                    return RedirectToAction("Backend", "Home");
                }
                else
                {
                    // TODO: validation later on...
                    return RedirectToAction("Create");
                }
            }
            catch
            {
                // TODO: validation later on...
                return RedirectToAction("Create");
            }
        }

        //
        // GET: /JobOpenings/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /JobOpenings/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /JobOpenings/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /JobOpenings/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /JobOpenings/Approve

        [Authorize(Roles = "Administrator, StoreManager")]
        public async Task<ActionResult> Approve(int id)
        {
            List<JobDAO> jobs = await ServerResponse<List<JobDAO>>.GetResponseAsync(ServiceURIs.ServiceJobUri);

KaskKiosk/Views/JobOpenings/Approve.cshtml
@{
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
    ViewBag.Title = "Approve Job Opening";
}

<h2>Approve Job Opening</h2>
@using (Html.BeginForm("Approve", "JobOpenings", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="section" id="section0">
        <h3>Are you sure you want to approve this job opening?</h3>
        <div class="form-group spacing" style="width:200px;float:left;">
            @Html.Label("Job Type:")
            @if (ViewBag.jobs != null)
            {
                foreach (var job in @ViewBag.jobs)
                {
                    if (job.JobID == @ViewBag.jobOpening.JobID)
                    {
                        @job.Title
                    }
                }
            }
        </div>
        <input type="hidden" name="JobOpeningID" id="JobOpeningID" value="@ViewBag.jobOpening.JobOpeningID" />
        <br style="clear:both;"/>
    </div>
    
    <a href="@Html.Encode("/JobOpenings/Index")" class="btn btn-danger">Cancel</a>@Html.Raw("&nbsp;&nbsp;&nbsp;")
    <input type="submit" id="submit" value="Approve" class="btn btn-success" />
}

KaskKiosk/Views/JobOpenings/Create.cshtml
@{
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
    ViewBag.Title = "Request Job Opening";
}

<h2>Request Job Opening</h2>
@using (Html.BeginForm("Create", "JobOpenings", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="section" id="section0">
        <div class="form-group spacing" style="width:200px;float:left;">
            @Html.Label("Job Type:")
            @if (ViewBag.jobs != null)
            {
                <select class="form-control" name="JobID" id="JobID">
                @foreach (var job in @ViewBag.jobs)
                {
                    <option value="@job.JobID">@job.Title</option>
                }
                </select>
            }
        </div>
        <br style="clear:both;"/>
        <div class="form-group spacing" style="width:200px;float:left;">
            @Html.Label("Job for Store:")
            @if (ViewBag.stores != null)
            {
                <select class="form-control" name="StoreID" id="StoreID">
                @foreach (var store in @ViewBag.stores)
                {
                    <option value="@store.StoreID">@store.Location</option>
                }
                </select>
            }
        </div>
        <br style="clear:both;"/>
        <div class="form-group spacing" style="width:200px;float:left;">
            @Html.Label("Description:")<br />
            <textarea name="Description" id="Description" style="width:400px;"></textarea>
        </div>
        <br style="clear:both;"/>
    </div>
    
    <div class="section" id="section1">
        <div class="form-group spacing" style="width:200px;float:left;">
            @Html.Label("Skills Needed:")<br />
            @if (ViewBag.skills != null)
            {
                foreach (var skill in @ViewBag.skills)
                {
                    <input type="checkbox" name="Skill_@skill.SkillID" value="1" /> @skill.SkillName<br />
                }
            }
        </div>
        <br style="clear:both;"/>
    </div>
    
    <div class="section" id="section2">
        <div class="form-group spacing" style="width:400px;float:left;">
            @Html.Label("Short Answer Questions for Interview:")
            @if (ViewBag.saQuestions != null)
            {
                <select class="form-control" name="SAQuestion_1" id="SAQuestion_1">
                @foreach (var saQuestion in @ViewBag.saQuestions)
                {
                    <option value="@saQuestion.SAQuestionID">@saQuestion.SAQuestionDescription</option>
                }
                </select>
            }
        </div>
        <br style="clear:both;"/>

        <div class="form-group spacing" style="width:400px;float:left;">
            @Html.Label("Short Answer Questions for Interview:")
            @if (ViewBag.saQuestions != null)
            {
                <select class="form-control" name="SAQuestion_2" id="SAQuestion_2">
                @foreach (var saQuestion in @ViewBag.saQuestions)
                {
                    <option value="@saQuestion.SAQuestionID">@saQuestion.SAQuestionDescription</option>
                }
                </select>
            }
        </div>
        <br style="clear:both;"/>

        <div class="form-group spacing" style="width:400px;float:left;">
            @Html.Label("Short Answer Questions for Interview:")
            @if (ViewBag.saQuestions != null)
            {
                <select class="form-control" name="SAQuestion_3" id="SAQuestion_3">
                @foreach (var saQuestion in @ViewBag.saQuestions)
                {
                    <option value="@saQuestion.SAQuestionID">@saQuestion.SAQuestionDescription</option>
                }
                </select>
            }
        </div>
        <br style="clear:both;"/>
    </div>
    
    <a href="@Html.Encode("/Home/Backend")" class="btn btn-danger">Cancel</a>@Html.Raw("&nbsp;&nbsp;&nbsp;")
    <input type="submit" id="submit" value="Save" class="btn btn-success" />
}

KaskKiosk/Views/JobOpenings/Details.cshtml
@{
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
    ViewBag.Title = "Job Opening Details";
}

<h2>Job Opening Details</h2><br />
<div class="section" id="section0">
    <div class="form-group spacing" style="width:400px;float:left;">
        @Html.Label("Job Type:")<br />
        @if (ViewBag.jobs != null)
        {
            foreach (var job in @ViewBag.jobs)
            {
                if (ViewBag.jobOpening.JobID == @job.JobID)
                {
                    @job.Title
                }
            }
        }
    </div>
    <br style="clear:both;"/>
    <div class="form-group spacing" style="width:400px;float:left;">
        @Html.Label("Job for Store:")<br />
        @if (ViewBag.stores != null)
        {
            foreach (var store in @ViewBag.stores)
            {
                if (ViewBag.jobOpening.StoreID == @store.StoreID)
                {
                    @store.Location
                }
            }
        }
    </div>
    <br style="clear:both;"/>
    <div class="form-group spacing" style="width:400px;float:left;">
        @Html.Label("Description:")<br />
        @ViewBag.jobOpening.Description
    </div>
    <br style="clear:both;"/>
</div>
    
<div class="section" id="section1">
    <div class="form-group spacing" style="width:400px;float:left;">
        @Html.Label("Skills Needed:")<br />
        @if (ViewBag.jobRequirements != null)
        {
            foreach (var jobRequirement in @ViewBag.jobRequirements)
            {
                if (jobRequirement.JobOpeningID == ViewBag.jobOpening.JobOpeningID)
                {
                    foreach (var skill in @ViewBag.skills)
                    {
                        if (skill.SkillID == @jobRequirement.SkillID)
                        {
                            @skill.SkillName<br />
                        }
                    }
                }
            }
        }
    </div>
    <br style="clear:both;"/>
</div>

KaskKiosk/Views/JobOpenings/Index.cshtml
@model IEnumerable<KaskKiosk.AESApplicationServiceRef.JobOpeningDAO>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>All Job Openings</h2>
<table class="table table-striped">
    <tr>
        <th>id</th>
        <th>Open Date</th>
        <th>Title</th>
        <th>Approved</th>
        <th>Actions</th>
    </tr>
@foreach (var item in ViewBag.jobOpenings)
{
    <tr>
        <td>@item.JobOpeningID</td>
        <td>@item.OpenDate</td>
        <td>
            @if (ViewBag.jobs != null)
            {
                foreach (var job in @ViewBag.jobs)
                {
                    if (job.JobID == @item.JobID)
                    {
                        @job.Title
                    }
                }
            }
        </td>
        <td>@(item.Approved == 1 ? "Yes" : "No")</td>
        <td>
            @foreach (var allowedAction in @ViewBag.allowableActions)
            {
                if(allowedAction == "approve")
                {
                    @Html.ActionLink("Approve", "Approve", new { id=item.JobOpeningID })
                    @Html.Raw(" | ")
                }
                if(allowedAction == "reject")
                {
                    @Html.ActionLink("Reject", "Reject", new { id=item.JobOpeningID })
                    @Html.Raw(" | ")
                }
            }
            @Html.ActionLink("View Details", "Details", new { id=item.JobOpeningID })
        </td>
    </tr>
}
</table>

KaskKiosk/Views/JobOpenings/Reject.cshtml
@{
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
    ViewBag.Title = "Reject Job Opening";
}

<h2>Reject Job Opening</h2>
@using (Html.BeginForm("Reject", "JobOpenings", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="section" id="section0">
        <h3>Are you sure you want to reject this job opening?</h3>
        <div class="form-group spacing" style="width:200px;float:left;">
            @Html.Label("Job Type:")
            @if (ViewBag.jobs != null)
            {
                foreach (var job in @ViewBag.jobs)
                {
                    if (job.JobID == @ViewBag.jobOpening.JobID)
                    {
                        @job.Title
                    }
                }
            }
        </div>
        <input type="hidden" name="JobOpeningID" id="JobOpeningID" value="@ViewBag.jobOpening.JobOpeningID" />
        <br style="clear:both;"/>
    </div>
    
    <a href="@Html.Encode("/JobOpenings/Index")" class="btn btn-danger">Cancel</a>@Html.Raw("&nbsp;&nbsp;&nbsp;")
    <input type="submit" id="submit" value="Reject" class="btn btn-success" />
}

KaskKiosk/Views/JobOpenings/ViewCurrentOpenings.cshtml
@model IEnumerable<KaskKiosk.AESApplicationServiceRef.JobOpeningDAO>

@{
    ViewBag.Title = "Current Openings";
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
}

<h2>Current Openings</h2>
@foreach (var item in ViewBag.jobOpenings)
{
    <table class="table table-striped table-bordered">
    <tr>
        <td>
            @Html.Label("Job Title:")
            @if (ViewBag.jobs != null)
            {
                foreach (var job in @ViewBag.jobs)
                {
                    if (job.JobID == @item.JobID)
                    {
                        @job.Title
                    }
                }
            }
        </td>
        <td style="width:200px;">
            @Html.Label("Location:")
            @if (ViewBag.stores != null)
            {
                foreach (var store in @ViewBag.stores)
                {
                    if (store.StoreID == @item.StoreID)
                    {
                        @store.Location
                    }
                }
            }
        </td>
        <td style="width:100px;">
            @Html.Label("Job#:")
            @item.ID
        </td>
        <td style="width:200px;">
            @Html.Label("Opening Date:")
            @item.OpenDate.ToString("yyyy-MM-dd")
        </td>
    </tr>
    <tr>
        <td colspan="4">
            @Html.Label("Job Description:")<br />
            @item.Description
            <div style="float:right;">
                <a href="/App/Create?JobOpeningIDReferenceNumber=@item.ID" class="btn btn-lg btn-default">Apply</a>
            </div>
        </td>
    </tr>
    </table>
}