KaskKiosk/Controllers/API/AssessmentController.cs
using KaskKiosk.AESApplicationServiceRef;
using System.Collections.Generic;
using System.ServiceModel;
using System.Web;
using System.Web.Http;

namespace KaskKiosk.Controllers.API
{
    public class AssessmentController : ApiController
    {
        // GET: /Assessment/
        [HttpGet]
        public IEnumerable<AssessmentDAO> GetAssessments()
        {
            AssessmentServiceClient client = new AssessmentServiceClient();

            try
            {
                IEnumerable<AssessmentDAO> result = client.GetAssessments();
                return result;
            }
            catch (FaultException<KaskServiceException> e)
            {
                throw new HttpException(e.Message);
            }
        }

        // GET: /Assessment/id
        [HttpGet]
        public AssessmentDAO GetAssessment(int id)
        {
            AssessmentServiceClient client = new AssessmentServiceClient();

            try
            {
                AssessmentDAO result = client.GetAssessmentByID(id);
                return result;
            }
            catch (FaultException<KaskServiceException> e)
            {
                throw new HttpException(e.Message);
            }
        }

        [HttpPost]
        public bool PostAssessment(AssessmentDAO assessment)
        {
            AssessmentServiceClient client = new AssessmentServiceClient();

            try
            {
                bool result = client.CreateAssessment(assessment);
                return result;
            }
            catch (FaultException<KaskServiceException> e)
            {
                throw new HttpException(e.Message);
            }
        }
    }
}

KaskKiosk/Controllers/AssessmentController.cs
using KaskKiosk.AESApplicationServiceRef;

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KaskKiosk.Controllers
{
    public class AssessmentsController : Controller
    {
        //
        // GET: /Assessments/

        [Authorize(Roles = "Administrator, HiringManager, StoreManager")]
        public async Task<ActionResult> Index()
        {
            var assessments = await ServerResponse<List<AssessmentDAO>>.GetResponseAsync(ServiceURIs.ServiceAssessmentUri);
            ViewBag.assessments = assessments;
            return View();
        }

        //
        // GET: /Assessments/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Assessments/Create
        [AllowAnonymous]
        public async Task<ActionResult> Create(int id)
        {
            // TODO: in the future, use more specific API calls for these queries... or LINQ or something for this section

            // get skill information for questions
            // via job opening id in JobRequirement table
            List<JobRequirementDAO> jobRequirements = await ServerResponse<List<JobRequirementDAO>>.GetResponseAsync(ServiceURIs.ServiceJobRequirementUri);

            // find related skill ids
            List<int> relatedSkillIds = new List<int>();
            foreach (JobRequirementDAO requirementItem in jobRequirements)
            {
                if (requirementItem.JobOpeningID.Equals(id))
                    relatedSkillIds.Add(requirementItem.SkillID);
            }

            // then find related skill-questionbank items
            List<SkillQuestionBankDAO> skillQuestionBanks = await ServerResponse<List<SkillQuestionBankDAO>>.GetResponseAsync(ServiceURIs.ServiceSkillQuestionBankUri);

            List<int> relatedQuestionBankIds = new List<int>();
            foreach (SkillQuestionBankDAO skillQuestionBankItem in skillQuestionBanks)
            {
                if (relatedSkillIds.Contains(skillQuestionBankItem.SkillID))
                    relatedQuestionBankIds.Add(skillQuestionBankItem.QuestionBankID);
            }

            // then find related mc question banks
            List<QuestionBankDAO> questionBanks = await ServerResponse<List<QuestionBankDAO>>.GetResponseAsync(ServiceURIs.ServiceQuestionBankUri);
            
            HashSet<int> relatedMcQuestionIds = new HashSet<int>();

            // idea for this:
            // QuestionBankID -> QuestionID -> OptionID
            Dictionary<int, Dictionary<int, HashSet<int>>> relatedMcOptionsForMcQuestions = new Dictionary<int, Dictionary<int, HashSet<int>>>();

            foreach (QuestionBankDAO questionBankItem in questionBanks)
            {
                if (relatedQuestionBankIds.Contains(questionBankItem.QuestionBankID))
                {
                    // get related question ids
                    relatedMcQuestionIds.Add(questionBankItem.MCQuestionID);
                    
                    // get related question options for each question id
                    if (relatedMcOptionsForMcQuestions.ContainsKey(questionBankItem.MCQuestionID))
                    {
                        // key already exists, so just append
                        relatedMcOptionsForMcQuestions[questionBankItem.QuestionBankID][questionBankItem.MCQuestionID].Add(questionBankItem.MCOptionID);
                    }
                    else
                    {
                        // create new key, then append
                        relatedMcOptionsForMcQuestions.Add(questionBankItem.QuestionBankID, new Dictionary<int, HashSet<int>>());
                        relatedMcOptionsForMcQuestions[questionBankItem.QuestionBankID].Add(questionBankItem.MCQuestionID, new HashSet<int> { questionBankItem.MCOptionID });
                    }
                }
            }

            // for now, get a list of all mc questions (to use in the view)
            List<MCQuestionDAO> allMcQuestions = await ServerResponse<List<MCQuestionDAO>>.GetResponseAsync(ServiceURIs.ServiceMCQuestionUri);

            // for now, get a list of all mc options (to use in the view)
            List<MCOptionDAO> allMcOptions = await ServerResponse<List<MCOptionDAO>>.GetResponseAsync(ServiceURIs.ServiceMCOptionUri);

            // find applicant id from the previously submitted Application form
            var applieds = await ServerResponse<List<AppliedDAO>>.GetResponseAsync(ServiceURIs.ServiceAppliedUri);
            int applicantID = applieds.Last().ApplicantID;

            ViewBag.baseURL = Url.Content("~/");
            ViewBag.allMcQuestions = allMcQuestions;
            ViewBag.allMcOptions = allMcOptions;
            ViewBag.relatedMcQuestionIds = relatedMcQuestionIds;
            ViewBag.relatedMcOptionsForMcQuestions = relatedMcOptionsForMcQuestions;
            ViewBag.jobOpeningIDReferenceNumber = id;
            ViewBag.applicantID = applicantID;
            return View();
        }

        //
        // POST: /Assessments/Create

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Create(FormCollection collection)
        {
            try
            {
                if (Request.Form["acknowledgeAccurateDataCheckbox"] != null)
                {
                    // save application form data back to database through service
                    using (HttpClient httpClient = new HttpClient())
                    {
                        httpClient.BaseAddress = new Uri("http://localhost:51309");
                        httpClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                        HttpResponseMessage result = new HttpResponseMessage();
                        string resultContent = "";

                        // find applicant id from the previously submitted Application form, if available
                        int applicantID = 0;
                        if (Convert.ToInt32(Request.Form["applicantID"]) > 0)
                        {
                            applicantID = Convert.ToInt32(Request.Form["applicantID"]);
                        }
                        // otherwise, get last applicant id from database
                        else
                        {
                            var applieds = await ServerResponse<List<AppliedDAO>>.GetResponseAsync(ServiceURIs.ServiceAppliedUri);
                            applicantID = applieds.Last().ApplicantID;
                        }

                        // gather AssessmentOpening form data
                        AssessmentDAO assessment = new AssessmentDAO();
                        assessment.ApplicantID = applicantID;

                        // and save the mc answer chosen by applicant

                        // first, parse the questionBankId and optionId of checkbox chosen by user

                        int parsedQuestionBankId = 0;
                        int parsedQuestionId = 0;
                        int parsedOptionId = 0;

                        var questionBankAnswers = await ServerResponse<List<QuestionBankDAO>>.GetResponseAsync(ServiceURIs.ServiceQuestionBankUri);

                        // TODO: change the hardcoded "50" into some sort of variable
                        // (i.e. the length of all possible questionBank ids, questions, and options)
                        for (int i = 0; i < 50; i++)
                        {
                            for (int j = 0; j < 50; j++)
                            {
                                for (int k = 0; k < 50; k++)
                                {
                                    try
                                    {
                                        if (Request.Form["MCOption_" + i + "_" + j + "_" + k] != null)
                                        {
                                            parsedQuestionBankId = i;
                                            parsedQuestionId = j;
                                            parsedOptionId = k;

                                            // check to see if answer is valid or "correct"
                                            // if not valid, redirect to "sorry" screen
                                            foreach (QuestionBankDAO qbItem in questionBankAnswers)
                                            {
                                                if (qbItem.QuestionBankID.Equals(parsedQuestionBankId))
                                                {
                                                    if (!parsedOptionId.Equals(Convert.ToInt32(qbItem.MCCorrectOption)))
                                                    {
                                                        // delete failed application
                                                        var applications = await ServerResponse<List<ApplicationDAO>>.GetResponseAsync(ServiceURIs.ServiceApplicationUri);
                                                        int applicationID = applications.Last().ApplicationID;

                                                        var resultTwo = await httpClient.DeleteAsync(ServiceURIs.ServiceApplicationUri.ToString() + "/" + applicationID.ToString());

                                                        // delete failed applicant
                                                        resultTwo = await httpClient.DeleteAsync(ServiceURIs.ServiceApplicantUri.ToString() + "/" + applicantID.ToString());

                                                        // delete failed applied
                                                        resultTwo = await httpClient.DeleteAsync(ServiceURIs.ServiceAppliedUri.ToString() + "/" + applicantID.ToString());

KaskKiosk/Views/Assessments/Create.cshtml
@{
    Layout = "~/Views/Shared/_PublicKioskAssessmentLayout.cshtml";
    ViewBag.Title = "Create.cshtml";
}

<ul id="menu" class="text-center">
    <li><a href="@ViewBag.baseURL"><span class="glyphicon glyphicon-home"></span></a></li>
    <li data-menuanchor="welcome" class="active"><a href="#welcome">Welcome</a></li>
    <li data-menuanchor="assessmentQuestions" class="active"><a href="#assessmentQuestions">Assessment Questions</a></li>
    <li data-menuanchor="submitAssessment" class="active"><a href="#submitAssessment">Submit Assessment</a></li>
</ul>

@using (Html.BeginForm("Create", "Assessments", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="section" id="section0">
        <div class="cover">
            <h1 class="cover-heading">Welcome to Kask Kiosk Assessment Screening</h1>
            <p class="lead">
                Click the <button id="moveDownExample" class="btn btn-info">Next &rarr;</button> button to begin.
            </p>
        </div>
    </div>
    
    <div class="section" id="section1">
        <h2>Assessment Questions</h2>
        <p class="lead italic">Please answer the following questions...</p>
        <div class="form-group spacing" style="width:800px;float:left;">
            <table>
            @if (ViewBag.allMcQuestions != null)
            {
                foreach (var mcQuestionRelatedId in @ViewBag.relatedMcQuestionIds)
                {
                    foreach (var mcQuestion in @ViewBag.allMcQuestions)
                    {
                        if (mcQuestionRelatedId == mcQuestion.MCQuestionID)
                        {
                            @Html.Raw("<tr>");
                            @Html.Raw("<td>");
                            @mcQuestion.MCQuestionDescription @Html.Raw("&nbsp;&nbsp;")
                            @Html.Raw("</td>");
                            @Html.Raw("<td>");
                            try
                            {
                                <!-- brute force loop for now... -->
                                for (int questionBankIdIndex = 0; questionBankIdIndex < 50; questionBankIdIndex++)
                                {
                                    try
                                    {
                                        <!-- loop through related mc options, if key exists -->
                                        foreach (var relatedMcOptionsForMcQuestionId in @ViewBag.relatedMcOptionsForMcQuestions[questionBankIdIndex][mcQuestionRelatedId])
                                        {
                                            foreach (var mcOption in @ViewBag.allMcOptions)
                                            {
                                                if (relatedMcOptionsForMcQuestionId == mcOption.MCOptionID)
                                                {
                                                <input type="radio" name="MCOption_@questionBankIdIndex@Html.Raw("_")@mcQuestion.MCQuestionID@Html.Raw("_")@mcOption.MCOptionID" value="1" /> @mcOption.MCOptionDescription @Html.Raw("&nbsp;&nbsp;")
                                                }
                                            }
                                        }
                                    }
                                    catch { }
                                }
                            }
                            catch
                            { }
                            @Html.Raw("</td>");
                        }
                    }
                    @Html.Raw("</tr>");
                }
            }
            </table>
        </div>
        <br style="clear:both;"/>
    </div>
    
    <div class="section center" id="section2">
        <input type="hidden" name="JobOpeningIDReferenceNumberOnAssessment" id="JobOpeningIDReferenceNumberOnAssessment" value="@ViewBag.jobOpeningIDReferenceNumber" readonly />
        <input type="hidden" name="ApplicantID" id="ApplicantID" value="@ViewBag.applicantID" readonly />
        <input type="checkbox" name="acknowledgeAccurateDataCheckbox" /> I acknowledge that I have provided accurate information<br /><br />
        <a href="@ViewBag.baseURL" class="btn btn-danger">Cancel Application</a>&nbsp;&nbsp;&nbsp;
        <input type="submit" id="submit" value="Submit Application" class="btn btn-success" />
    </div>
}

<div class="center">
    <button id="moveUp" class="btn btn-info">&larr; Prev</button>    
    <button id="moveDown" class="btn btn-info">Next &rarr;</button>
</div>

<!-- create more space at bottom of view page for now... -->
<br />
<br />
<br />
<br />
<br />
<br />
<br />

KaskKiosk/Views/Assessments/Sorry.cshtml
@{
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
    ViewBag.Title = "Sorry.cshtml";
}

<h2>Sorry...</h2>
<h3>Thank you for your interest!<br />
Unfortunately, we cannot hire you at this time.<br />
All the best for your next opportunity, though!</h3>